#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>
#include <driver/spi_master.h>
#include <esp_lcd_panel_vendor.h>

#include "moss_shared_audio.h"

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

// NS4150B CTRL is wired to GPIO48 (IO48_SPK_EN).
#define AUDIO_CODEC_PA_PIN GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

/*
 * 0.96" ST7735S LCD — from bread-compact-wifi-096lcd.
 * SPI: MOSI=41 SCK=42 CS=47 DC=39 RST=40 BL=21
 */
#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_41
#define DISPLAY_SPI_SCK_PIN GPIO_NUM_42
#define DISPLAY_SPI_CS_PIN GPIO_NUM_47
#define DISPLAY_DC_PIN GPIO_NUM_39
#define DISPLAY_RST_PIN GPIO_NUM_40

#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 80
// 预分配 DMA bounce, 避免对话/唤醒时 SPI 再向内部 SRAM malloc.
#define DISPLAY_LCD_BOUNCE_ROWS 16
#define DISPLAY_SPI_MAX_TRANSFER (DISPLAY_WIDTH * DISPLAY_LCD_BOUNCE_ROWS * sizeof(uint16_t))
#define DISPLAY_SWAP_XY true
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false

#ifndef DISPLAY_RGB_ORDER
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#endif

#define DISPLAY_OFFSET_X_DEFAULT 1
#define DISPLAY_OFFSET_Y_DEFAULT 26
#ifndef DISPLAY_OFFSET_X
#define DISPLAY_OFFSET_X DISPLAY_OFFSET_X_DEFAULT
#endif
#ifndef DISPLAY_OFFSET_Y
#define DISPLAY_OFFSET_Y DISPLAY_OFFSET_Y_DEFAULT
#endif

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_21
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

/*
 * Moss MCP peripherals (migrated from moss-xiaozhi).
 * Pins do not overlap the 0.96" LCD SPI bus above.
 */
#define MOSS_MCP_PERIPHERALS_ENABLE 1

#define MOSS_LAMP_74HC595_SER_PIN GPIO_NUM_3
#define MOSS_LAMP_74HC595_RCK_PIN GPIO_NUM_4
#define MOSS_LAMP_74HC595_SCK_PIN GPIO_NUM_5
#define MOSS_LAMP_EYE_PIN GPIO_NUM_15
#define MOSS_EYE_MOTOR_IN1_PIN GPIO_NUM_10
#define MOSS_EYE_MOTOR_IN2_PIN GPIO_NUM_11
#define MOSS_EYE_MOTOR_PWM_PIN GPIO_NUM_9
#define MOSS_IR_UART_TX_PIN GPIO_NUM_17
#define MOSS_IR_UART_RX_PIN GPIO_NUM_18
#define MOSS_IR_UART_PORT UART_NUM_2

// 1=接入实时音谱插件 (聆听=麦克风, 说话=播放). 0=拔掉, 信号弹窗回退到时间驱动波形.
#ifndef MOSS_AUDIO_WAVE_PLUGIN
#define MOSS_AUDIO_WAVE_PLUGIN 1
#endif

#endif  // _BOARD_CONFIG_H_
