#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE true

// ES7210 MIC1 模拟增益（dB）。唤醒偏钝就加大，误唤醒/破音就减小。
// 硬件 PGA 大约到 ~37.5；再高由驱动钳位。常用范围 28~37.5。
#define AUDIO_CODEC_INPUT_GAIN 37.5f

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

// NS4150B CTRL is wired to GPIO48 (IO48_SPK_EN), not PCA9557.
#define AUDIO_CODEC_PA_PIN GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

/*
 * Moss MCP peripherals (migrated from moss-xiaozhi).
 * These pins overlap the DVP camera bus on lichuang-derived layouts, so the
 * camera is disabled when MOSS_MCP_PERIPHERALS_ENABLE is 1.
 */
#define MOSS_MCP_PERIPHERALS_ENABLE 1

#define MOSS_LAMP_74HC595_SER_PIN GPIO_NUM_3
#define MOSS_LAMP_74HC595_RCK_PIN GPIO_NUM_4
#define MOSS_LAMP_74HC595_SCK_PIN GPIO_NUM_5
#define MOSS_LAMP_EYE_PIN GPIO_NUM_15
#define MOSS_EYE_MOTOR_IN1_PIN GPIO_NUM_10
#define MOSS_EYE_MOTOR_IN2_PIN GPIO_NUM_11
#define MOSS_EYE_MOTOR_PWM_PIN GPIO_NUM_9
#define MOSS_IR_UART_TX_PIN GPIO_NUM_17
#define MOSS_IR_UART_RX_PIN GPIO_NUM_18
#define MOSS_IR_UART_PORT UART_NUM_2

/* Camera pins (unused while MOSS_MCP_PERIPHERALS_ENABLE=1) */
#define CAMERA_PIN_PWDN GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_PIN_XCLK GPIO_NUM_5
#define CAMERA_PIN_SIOD GPIO_NUM_1
#define CAMERA_PIN_SIOC GPIO_NUM_2

#define CAMERA_PIN_D7 GPIO_NUM_9
#define CAMERA_PIN_D6 GPIO_NUM_4
#define CAMERA_PIN_D5 GPIO_NUM_6
#define CAMERA_PIN_D4 GPIO_NUM_15
#define CAMERA_PIN_D3 GPIO_NUM_17
#define CAMERA_PIN_D2 GPIO_NUM_8
#define CAMERA_PIN_D1 GPIO_NUM_18
#define CAMERA_PIN_D0 GPIO_NUM_16
#define CAMERA_PIN_VSYNC GPIO_NUM_3
#define CAMERA_PIN_HREF GPIO_NUM_46
#define CAMERA_PIN_PCLK GPIO_NUM_7

#define XCLK_FREQ_HZ 20000000

#endif  // _BOARD_CONFIG_H_
