#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#include "moss_shared_audio.h"

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

// Source tree leftover used GPIO48 as BUILTIN_LED and PA=NC.
// This PCB family uses GPIO48 as NS4150B CTRL (IO48_SPK_EN), same as pcb-v1.
#define AUDIO_CODEC_PA_PIN GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

/*
 * SSD1306 128x64 OLED on a dedicated I2C bus (port 0).
 * Pins match the source moss-pcb-board / pcb-v1: SDA=6 SCL=7.
 * Codec remains on I2C port 1 (SDA=1 SCL=2).
 */
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_SDA_PIN GPIO_NUM_6
#define DISPLAY_SCL_PIN GPIO_NUM_7

#define MOSS_MCP_PERIPHERALS_ENABLE 1

#define MOSS_LAMP_74HC595_SER_PIN GPIO_NUM_3
#define MOSS_LAMP_74HC595_RCK_PIN GPIO_NUM_4
#define MOSS_LAMP_74HC595_SCK_PIN GPIO_NUM_5
#define MOSS_LAMP_EYE_PIN GPIO_NUM_15
#define MOSS_IR_UART_TX_PIN GPIO_NUM_17
#define MOSS_IR_UART_RX_PIN GPIO_NUM_18
#define MOSS_IR_UART_PORT UART_NUM_2

#endif  // _BOARD_CONFIG_H_
